capstone project personal blog website
BranBayou/capstonePro1-personal-blog pull request #2
Opened 2023-03-22 13:57 UTC by BranBayou

- First I created 2 pages index.html and about.html.
- I made these two pages responsive by building for the desktop version and mobile version.
- I put links for the home page and about page to make the website responsive when the user clicks the logo or the about nav link.
- I created a mobile hamburger menu when the screen gets small than 768px.]
- I created a dynamically generated section for featured blogs using a javascript array object.
- I checked for linter errors.
- I recorded a loom video to present my capstone project website: https://www.loom.com/share/916b01dc78ad4ece8bb25dd1148ac28d

2023-03-22 15:10 UTC, Ibizugbe requested changes
Hi @BranBayou 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/226943537-2da7cfba-14be-436d-a3cd-c8421d445329.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍
- [x] Github flow practice has been used👍
- [x] An array of object containing the information of the various speakers has been created 👍.
- [x] The speakers section is generated dynamically using JavaScript👍.
- [x] Video presentation looks great👍


## Required Changes ♻️

- [ ] Your about page looks great on desktop👍 but let's stick to the design even on mobile😉 your about page looks very different from the design😉 Kindly ensure to use the [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) as a guideline and make the page responsive😉 don't forget we are required to stick to the given [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) in this project😎
<img width="281" alt="your about mobile" src="https://user-images.githubusercontent.com/64643995/226944752-09ac0ab7-c37f-4d66-bf93-2088b5226f60.png">

- [ ] Kindly use the semantic `hx` hierarchy rule when chosing the header to use all through your project😉 Use `h1` for the intro or main header of the page, use `h2` for the main header of each section and use `h3`, `h4` etc as you go down the hierarchy. this helps screen readers to understand the position of a heading. for instance, a `h2` under a `h1` shows that the `h2` is a heading under the `h1` heading. Kindly make the necessary change all through your project😉
<img width="488" alt="semantic respect" src="https://user-images.githubusercontent.com/64643995/226947577-2ae39ebc-aed2-4822-ac8b-0257c576419b.png">

- [ ] Just as shown in the image above, kindly ensure all your `alt` attribute contents are filled with a descriptive text that gives information about the image😉 This makes your images meaningful to screen readers and also give your users an idea of what the image is about when the network is slow or the link is broken😉


_Check the comments under the review._

## Optional suggestions
-  _no optional suggestion_
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 15:10 UTC, Ibizugbe commented on index.html
> +        </div>
Nice job on your landing page👍 But let's ensure to stick to the design by taking away the top dark bar on the mobile screen😉 the top dark bar should only be present on the desktop screen as displayed in the design😉
also, kindly take away the white space and ensure the background image is uniform just as presented in the design😉
<img width="292" alt="NO TOP BAR" src="https://user-images.githubusercontent.com/64643995/226941316-0253fc18-68a4-46cf-928e-b3fa55022b44.png">

2023-03-22 19:19 UTC, huseyinbiyik requested changes
Hi @BranBayou 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter set up well and checks pass 🟢
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝


 ## Required Changes ♻️
- As the previous reviewer requested, please make your web page responsive and follow the design guideline. Below, you can find the issues.
- - The about page still has a horizontal overflow.
![Screen Recording 2023-03-22 at 9 19 31 PM](https://user-images.githubusercontent.com/25887253/227012073-33be5d92-103c-4a94-87d5-86b02fbf8d60.gif)

- - Please add space around the images like on the design guidelines.
<img width="490" alt="Screenshot 2023-03-22 at 9 24 57 PM" src="https://user-images.githubusercontent.com/25887253/227011761-e4f0ee8d-e072-4953-9c2d-0b178d9a48d7.png">
<img width="476" alt="Screenshot 2023-03-22 at 9 20 20 PM" src="https://user-images.githubusercontent.com/25887253/227011749-8372935d-6ed0-4e05-83dd-5e4337fd92b9.png">

- - Kindly fix the section title and make sure it matches the design guideline.
<img width="490" alt="Screenshot 2023-03-22 at 9 27 03 PM" src="https://user-images.githubusercontent.com/25887253/227012284-11205f4f-5677-4346-a1f5-f4d390a7cb13.png">
<img width="490" alt="Screenshot 2023-03-22 at 9 25 09 PM" src="https://user-images.githubusercontent.com/25887253/227012278-7615fb8a-97f6-4955-8a40-624c8367de9d.png">

- - Please fix the overflowed logo. Some of it are out of the screen like below.
<img width="490" alt="Screenshot 2023-03-22 at 9 27 23 PM" src="https://user-images.githubusercontent.com/25887253/227012452-d585bd53-6baa-4296-9f29-d379255d3352.png">


_Check the comments under the review._

## Optional suggestions
- Kindly make sure you can navigate from about page to home page on mobile version/mobile navigation. In this way, you will enhance your UX.
- Please stick to the design and align your top black nav vertically aligned. There is more space under texts/icons 👍 
<img width="790" alt="Screenshot 2023-03-22 at 9 28 13 PM" src="https://user-images.githubusercontent.com/25887253/227011052-6568d244-0d67-4a5e-aa5d-d99f100618e4.png">
- Please use descriptive branch names instead of "feature" (e.g.: refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. [Check](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) more to learn more about this.


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 19:19 UTC, huseyinbiyik commented on index.html
> +      <h1 class="pro-intro mt-5">Recent Blogs</h1>
As the previous reviewer requested, please set your hx element hierarchically. Kindly use the h1 element on the page once. h1 refers to the most important element on the page. You can check this link to learn more: https://techstacker.com/seo-only-use-h1-elements-once-per-page/

hx elements used for SEO and accessibility of your page. It is not about the size of the text element. So the most important element is h1 and used it once, and it goes down h2,h3...h6. You can use h2 for **each** section title: 
-index.html
Recent Blogs
Featured Blogs
Partners
-about.html
Creative Commons b personal blog 2023 Logo
See tha past bloges by b personal blog

You can also check this [project](https://github.com/huseyinbiyik/world-tomato-forum) to understand more.

2023-03-23 11:35 UTC, IngDavidTM requested changes
## Hi @BranBayou  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] Your page styling looks good as per the previous request :+1:, but it's important to note that there is still a horizontal scroll on the about page when it's viewed on the mobile version. This can impact the user experience and may result in content being cut off or inaccessible. Therefore, it's important to fix this issue to ensure proper functionality and usability on all devices :+1:.


https://user-images.githubusercontent.com/105117832/227188790-cdd3b371-c6fb-4b24-b3fb-d8b4c3c00c16.mp4

- [ ] Your page layout looks good, but as previously mentioned, it's important to match it as closely as possible with the template. To achieve this, it would be better to add some space to each side of the images on the about page in the mobile version. This will help to align the images with the template and enhance the overall visual appeal of the page.

**Your design**

![Screenshot from 2023-03-23 06-25-50](https://user-images.githubusercontent.com/105117832/227189733-a6e6d541-6723-41a2-a65f-e4d5ea3cb3ea.png)

**Template**

![Screenshot from 2023-03-23 06-25-17](https://user-images.githubusercontent.com/105117832/227189777-af3db11b-d069-42cb-bc70-ab9dd49a575a.png)

- [ ] As requested by the previous reviewer kindly fix the section title on the about page on the mobile version and make sure it matches the design guideline because now everything is overlapping.

**Your design**

![Screenshot from 2023-03-23 06-29-41](https://user-images.githubusercontent.com/105117832/227191156-b95c164a-d0aa-43cb-9a03-1af7b950e22f.png)

**Template**

![Screenshot from 2023-03-23 06-33-37](https://user-images.githubusercontent.com/105117832/227191323-fdc93a05-8bd4-4627-b69f-2fc1b4a6fbd3.png)

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 13:28 UTC, gemmen29 approved these changes
Hi @BranBayou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 13:30 UTC, merged